# Defines the cost per token for different LLM providers and models (in USD)
llm_costs:
  google_gemini:
    gemini-2.5-flash-lite:
      input_cost_per_million_tokens: 0.10
      output_cost_per_million_tokens: 0.40
  openai:
    gpt-5-nano:
      input_cost_per_million_tokens: 0.05
      output_cost_per_million_tokens: 0.40